name: vduq
channels:
    - gpytorch
    - pytorch
    - defaults
dependencies:
    - python>=3.6
    - gpytorch>=1.2.1
    - pytorch
    - torchvision
    - ignite
    - tensorboard
    - tqdm
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
